### ISSUE TITLE
Problema al tener imagenes en distintas carpetas

### ISSUE THREAD

**Issue by tfloxolodeiro** [uqbar-project/wollok-run-client#25]
En [este juego](https://github.com/wollok/MarioBrossGame) todas las imagenes que se usan en el juego estan dentro de una misma carpeta y, a parte, hay otra carpeta que tiene una imagen que no se usa en el juego. Esto rompe todo porque la forma actual de obtener el nombre de la carpeta de assets (donde estan las imagenes que se usan en el juego) asume que todas las imagenes que hay en el repo estan en la misma carpeta de assets, lo cual en retrospectiva no tiene tanto sentido y en algunos casos de juegos probados esto estuvo andando de suerte nomas.

**Comment by PalumboN** [comment]
Dijimos de leer el archivo `build.properties` para:
- Saber dónde se encuentra el proyecto. Ya que se encuentran en la misma carpeta
Y leyendo el contenido podemos saber dónde están los recursos:
- El atributo `source..` contiene donde están los fuentes y las imágenes. Si solo está la carpeta `src`, usar la misma para ambos.

Chusmear esto: https://www.npmjs.com/package/java-properties
