### ISSUE TITLE
Muchos juegos no se pueden correr por usar ++ y -- ¿Qué hacemos?

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-run-client#27]
El plan que propongo, ya que esto se va a deprecar muy pronto, es arreglar los juegos a mano:
- Forkearlos
- Cambiar los `++` por `+= 1`
- Tirar un PR
- Actualizar la planilla con el nuevo repo (fork)
- Probar con eso arreglado

**Comment by lspigariol** [comment]
me parece un buen plan
los pondriamos en la orga wollok, no?
tal vez, a algunos se pueda aprovechar a hacerles algun ajuste más
