### ISSUE TITLE
Mejorar el ingreso de url del repo

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-run-client#30]
@faloi dice: lo que hay que poner en el campo ese es el **slug** (orga/repo) y no la URL como dice... de hecho si ponés la URL se queda cargando infinitamente
![image](https://user-images.githubusercontent.com/4098184/95268233-45963100-080d-11eb-82d8-c76a767afd3b.png)

-----

Estaría bueno que se banque tanto la url completa (que supongo que es lo que más se va a usar), como el slug como el `.git`. Habría que jugar un poco con el string.

También estaría bueno tener un autocompletado como el de classroom:
![image](https://user-images.githubusercontent.com/4098184/95268355-8e4dea00-080d-11eb-9212-7a8a10e8de6e.png)

**Comment by faloi** [comment]
:call_me_hand:

**Comment by PalumboN** [comment]
@estefaniamiguel dice: También estaría bueno permitir clonarse repos de gitlab!
