### ISSUE TITLE
Poder levantar repos de gitlab

### ISSUE THREAD

**Issue by tfloxolodeiro** [uqbar-project/wollok-run-client#32]
Ahora solo se pueden usar repos en github, pero se tendrían que poder levantar repos de gitlab.

**Comment by PalumboN** [comment]
Hay problemas para traer las imágenes raw de gitlab. Investigar cómo obtenerlo sin que tire `403` / CORS, o aún mejor ver de si se pueden usar las imágenes clonadas localmente.
